services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: evan
      POSTGRES_PASSWORD: evan123
      POSTGRES_DB: baseball_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: